# Generated by Django 6.0.6 on 2026-06-11 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEstanque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estanque_id', models.CharField(max_length=100, unique=True)),
                ('nombre_estanque', models.CharField(default='Estanque', max_length=150)),
                ('temp_min', models.FloatField(default=20.0)),
                ('temp_max', models.FloatField(default=30.0)),
                ('ph_min', models.FloatField(default=6.5)),
                ('ph_max', models.FloatField(default=8.5)),
                ('tds_min', models.FloatField(default=0.0)),
                ('tds_max', models.FloatField(default=500.0)),
                ('oxigeno_min', models.FloatField(default=5.0)),
                ('oxigeno_max', models.FloatField(default=20.0)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
