# Generated by Django 6.0.6 on 2026-06-11 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estanque_id', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=50)),
                ('rango_min', models.FloatField(default=0.0)),
                ('rango_max', models.FloatField(default=100.0)),
            ],
        ),
    ]
